name: cbe_analyzer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
